server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db:3306/pdfscanner
    username: testuser
    password: testpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform:   org.hibernate.dialect.MySQL8Dialect